version: '3.7'

volumes:
  mongogeddata:

services:
#Beware: in order to work with other services from ged handler the network ged_network must be created in Docker:
#command line: $ docker network create ged_network
  mongo:
    image: mongo:5.0.6-focal
    restart: always
    environment:

      MONGO_INITDB_ROOT_PASSWORD: rootmongopwd

      MONGO_INITDB_ROOT_USERNAME: root

    volumes:
      - mongogeddata:/data/db
      - $PWD/mongo_ged.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    networks:
      - ged_network

    ports:
      - "27017:27017"

networks:
  ged_network:
    external: true
