version: '3.7'

volumes:
  mongogeddata:

services:

  ged_handler:
    image: robinatorondocker/ged-handler
    restart: always
    environment:
      'URL_MONGO': "mongo:27017"

      'USR_MONGO': "root"

      'PWD_MONGO': "rootmongopwd"

      'SECRET_KEY': "11088b752484acda51943b487d8657e142e91e085187c110e0967650e7526784"

      'URL_FRONT': 'http://localhost:8080'

    volumes:
      - $PWD/logs_preprod.log:/usr/src/app/app_logs.json

    ports:
      - "5555:8000"

  mongo:
    image: mongo:5.0.6-focal
    restart: always
    environment:

      MONGO_INITDB_ROOT_PASSWORD: rootmongopwd

      MONGO_INITDB_ROOT_USERNAME: root

    volumes:
      - mongogeddata:/data/db
      - $PWD/mongo_ged.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    #port publishing to be removed in production
    ports:
      - "27017:27017"