version: '3.7'

volumes:
  mongodata:

services:

  mongo:
    image: mongo:5.0.6-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: rootmongopwd
      MONGO_INITDB_ROOT_USERNAME: root

    volumes:
      - mongodata:/data/db
      - $PWD/mongo_ged.js:/mongo_ged.js:ro
      - $PWD/init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh

    ports:
      - "27017:27017"
