version: '3.7'

services:
#Beware: in order to work with other services from ged handler the network ged_network must be created in Docker:
#command line: $ docker network create ged_network

  ged_handler:
    image: robinatorondocker/ged-handler
    restart: always
    environment:
      'URL_MONGO': "mongo:27017"

      'USR_MONGO': "root"

      'PWD_MONGO': "rootmongopwd"

      'SECRET_KEY': "11088b752484acda51943b487d8657e142e91e085187c110e0967650e7526784"

      'URL_FRONT': 'http://localhost:8080'

    networks:
      - ged_network

    ports:
      - "5555:8000"

networks:
  ged_network:
    external: true
